"""
Pipeline Enhancement Wrapper - V5.0
Adds 6 new CSV outputs to existing pipeline
"""

import pandas as pd
import sys
from pathlib import Path

# Import our new modules
from benchmarks import INDUSTRY_BENCHMARKS, assess_vs_benchmark
from analytics import (
    calculate_revenue_intelligence,
    forecast_30_days,
    score_campaign_health,
    analyze_cohorts,
    analyze_call_timing,
    validate_cancellation_counts,
)

def load_existing_csvs(date_str=None):
    """Load the CSVs generated by transform_clean.py"""
    print("Loading existing CSVs...")
    
    # Determine output directory
    if date_str:
        output_dir = Path(f'outputs/{date_str}')
    else:
        # Find most recent output directory
        outputs_dir = Path('outputs')
        if not outputs_dir.exists():
            print(f"ERROR: outputs/ directory not found!")
            print(f"Current directory: {Path.cwd()}")
            sys.exit(1)
        
        # Get most recent date folder
        date_folders = sorted([d for d in outputs_dir.iterdir() if d.is_dir()], reverse=True)
        if not date_folders:
            print(f"ERROR: No date folders found in outputs/")
            sys.exit(1)
        
        output_dir = date_folders[0]
        print(f"  Using most recent output: {output_dir}")
    
    data = {}
    required_files = [
        'phiwe_calls.csv',
        'phiwe_bookings.csv',
        'phiwe_daily_performance.csv',
        'phiwe_call_timing.csv',
        'phiwe_booking_window_analysis.csv'
    ]
    
    for filename in required_files:
        filepath = output_dir / filename
        if not filepath.exists():
            print(f"ERROR: {filename} not found in {output_dir}!")
            print(f"Please run transform_clean.py first to generate base CSVs")
            sys.exit(1)
        
        data[filename.replace('phiwe_', '').replace('.csv', '')] = pd.read_csv(filepath)
        print(f"  ✓ Loaded {filename}")
    
    return data, output_dir

def generate_benchmarks_comparison(calls, bookings, output_dir):
    """Generate benchmark comparison CSV"""
    print("\nGenerating benchmarks comparison...")
    
    # Calculate actual metrics
    total_calls = len(calls)
    total_bookings = len(bookings)
    total_shows = bookings['has_show'].sum()
    # Pure cancellations: exclude rows where has_show=1 (attended leads whose
    # current_status was later set to Cancelled — has_show is authoritative).
    pure_cancellations = int(((bookings['is_cancelled'] == 1) & (bookings['has_show'] != 1)).sum())
    total_no_shows = bookings['is_no_show'].sum()
    connected_calls = calls['is_connected'].sum()

    # Rates — resolved = past appointments with final outcomes (excludes rescheduled)
    if 'is_resolved' in bookings.columns:
        resolved = bookings[bookings['is_resolved'] == 1]
    elif 'is_past' in bookings.columns:
        resolved = bookings[
            (bookings['is_past'] == 1) &
            (~bookings['current_status'].str.contains('Rescheduled', na=False))
        ]
    else:
        resolved = bookings
    resolved_count = len(resolved)
    conversion_rate = total_bookings / total_calls if total_calls > 0 else 0
    show_rate = total_shows / resolved_count if resolved_count > 0 else 0
    # Cancel rate denominator = total bookings (not resolved) per campaign methodology.
    cancel_rate = pure_cancellations / total_bookings if total_bookings > 0 else 0
    no_show_rate = total_no_shows / resolved_count if resolved_count > 0 else 0
    engagement_rate = connected_calls / total_calls if total_calls > 0 else 0
    
    # Assess each metric
    metrics = []
    
    # Conversion rate
    conv_assessment = assess_vs_benchmark(conversion_rate, 'conversion_rate', higher_is_better=True)
    metrics.append({
        'metric': 'conversion_rate',
        'actual_value': round(conversion_rate, 4),
        'actual_pct': f"{conversion_rate*100:.1f}%",
        'benchmark_level': conv_assessment['level'],
        'benchmark_pct': f"{INDUSTRY_BENCHMARKS['conversion_rate']['average']*100:.1f}%",
        'rank': conv_assessment['rank'],
        'gap_pct': f"{conv_assessment['gap']*100:+.1f}%",
        'status': conv_assessment['status'],
        'icon': conv_assessment['icon']
    })
    
    # Show rate
    show_assessment = assess_vs_benchmark(show_rate, 'show_rate', higher_is_better=True)
    metrics.append({
        'metric': 'show_rate',
        'actual_value': round(show_rate, 4),
        'actual_pct': f"{show_rate*100:.1f}%",
        'benchmark_level': show_assessment['level'],
        'benchmark_pct': f"{INDUSTRY_BENCHMARKS['show_rate']['average']*100:.1f}%",
        'rank': show_assessment['rank'],
        'gap_pct': f"{show_assessment['gap']*100:+.1f}%",
        'status': show_assessment['status'],
        'icon': show_assessment['icon']
    })
    
    # No-show rate
    noshow_assessment = assess_vs_benchmark(no_show_rate, 'no_show_rate', higher_is_better=False)
    metrics.append({
        'metric': 'no_show_rate',
        'actual_value': round(no_show_rate, 4),
        'actual_pct': f"{no_show_rate*100:.1f}%",
        'benchmark_level': noshow_assessment['level'],
        'benchmark_pct': f"{INDUSTRY_BENCHMARKS['no_show_rate']['average']*100:.1f}%",
        'rank': noshow_assessment['rank'],
        'gap_pct': f"{noshow_assessment['gap']*100:+.1f}%",
        'status': noshow_assessment['status'],
        'icon': noshow_assessment['icon']
    })
    
    # Engagement rate
    engagement_assessment = assess_vs_benchmark(engagement_rate, 'engagement_rate', higher_is_better=True)
    metrics.append({
        'metric': 'engagement_rate',
        'actual_value': round(engagement_rate, 4),
        'actual_pct': f"{engagement_rate*100:.1f}%",
        'benchmark_level': engagement_assessment['level'],
        'benchmark_pct': f"{INDUSTRY_BENCHMARKS['engagement_rate']['average']*100:.1f}%",
        'rank': engagement_assessment['rank'],
        'gap_pct': f"{engagement_assessment['gap']*100:+.1f}%",
        'status': engagement_assessment['status'],
        'icon': engagement_assessment['icon']
    })
    
    # Cancel rate
    cancel_assessment = assess_vs_benchmark(cancel_rate, 'cancel_rate', higher_is_better=False)
    metrics.append({
        'metric': 'cancel_rate',
        'actual_value': round(cancel_rate, 4),
        'actual_pct': f"{cancel_rate*100:.1f}%",
        'benchmark_level': cancel_assessment['level'],
        'benchmark_pct': f"{INDUSTRY_BENCHMARKS['cancel_rate']['average']*100:.1f}%",
        'rank': cancel_assessment['rank'],
        'gap_pct': f"{cancel_assessment['gap']*100:+.1f}%",
        'status': cancel_assessment['status'],
        'icon': cancel_assessment['icon']
    })
    
    df = pd.DataFrame(metrics)
    output_file = output_dir / 'phiwe_benchmarks_comparison.csv'
    df.to_csv(output_file, index=False)
    print(f"  ✓ Created {output_file} ({len(df)} metrics)")
    
    return df

def generate_revenue_intelligence(calls, bookings, output_dir):
    """Generate revenue intelligence CSV"""
    print("\nGenerating revenue intelligence...")
    
    revenue_data = calculate_revenue_intelligence(bookings, calls, monthly_cost=3500, intro_price=69)
    
    # Convert to DataFrame
    df = pd.DataFrame([
        {'metric': k, 'value': v} for k, v in revenue_data.items()
    ])
    
    output_file = output_dir / 'phiwe_revenue_intelligence.csv'
    df.to_csv(output_file, index=False)
    print(f"  ✓ Created {output_file} ({len(df)} metrics)")
    
    return df

def generate_forecast(daily_performance, output_dir):
    """Generate 30-day forecast CSV"""
    print("\nGenerating 30-day forecast...")
    
    df = forecast_30_days(daily_performance)
    output_file = output_dir / 'phiwe_forecast_30_day.csv'
    df.to_csv(output_file, index=False)
    print(f"  ✓ Created {output_file} ({len(df)} scenarios)")
    
    return df

def generate_campaign_health(calls, bookings, output_dir):
    """Generate campaign health CSV"""
    print("\nGenerating campaign health score...")

    ramp_path = output_dir / 'phiwe_ramp_vs_target.csv'
    ramp_df = pd.read_csv(ramp_path) if ramp_path.exists() else None

    health_data = score_campaign_health(bookings, calls, monthly_cost=3500, ramp_df=ramp_df)
    
    # Flatten for CSV
    rows = []
    rows.append({'metric': 'total_score', 'value': health_data['total_score']})
    rows.append({'metric': 'max_score', 'value': health_data['max_score']})
    rows.append({'metric': 'level', 'value': health_data['level']})
    rows.append({'metric': 'churn_risk', 'value': health_data['churn_risk']})
    rows.append({'metric': 'churn_risk_pct', 'value': health_data['churn_risk_pct']})
    
    # Breakdown
    rows.append({'metric': 'performance_score', 'value': health_data['breakdown']['performance']['score']})
    rows.append({'metric': 'performance_max', 'value': health_data['breakdown']['performance']['max']})
    rows.append({'metric': 'engagement_score', 'value': health_data['breakdown']['engagement']['score']})
    rows.append({'metric': 'engagement_max', 'value': health_data['breakdown']['engagement']['max']})
    rows.append({'metric': 'goal_alignment_score', 'value': health_data['breakdown']['goal_alignment']['score']})
    rows.append({'metric': 'goal_alignment_max', 'value': health_data['breakdown']['goal_alignment']['max']})

    # Operational metrics — pre-computed so the dashboard never needs to aggregate
    # large raw tables (avoids Supabase PostgREST per-page row cap)
    total_calls = len(calls)
    meaningful  = int((calls['live_talk_min'].astype(float) >= 0.5).sum()) if 'live_talk_min' in calls.columns else 0
    total_bks   = len(bookings)
    has_show_col = next((c for c in bookings.columns if c.lower() in ('has_show',)), None)
    shows = int(bookings[has_show_col].astype(str).str.strip().isin(['1','True','true']).sum()) if has_show_col else 0
    cancelled   = int(bookings['current_status'].str.contains('Cancelled', na=False).sum()) if 'current_status' in bookings.columns else 0
    noshows     = int(bookings['current_status'].str.contains('No Show',   na=False).sum()) if 'current_status' in bookings.columns else 0
    resolved    = shows + noshows + cancelled

    rows.append({'metric': 'total_calls',       'value': total_calls})
    rows.append({'metric': 'meaningful_convs',  'value': meaningful})
    rows.append({'metric': 'connect_rate_pct',  'value': round(meaningful / total_calls * 100, 1) if total_calls else 0})
    rows.append({'metric': 'total_bookings',    'value': total_bks})
    rows.append({'metric': 'shows',             'value': shows})
    rows.append({'metric': 'show_rate_pct',     'value': round(shows / resolved * 100, 1) if resolved else 0})
    rows.append({'metric': 'booking_rate_pct',  'value': round(total_bks / meaningful * 100, 1) if meaningful else 0})

    df = pd.DataFrame(rows)
    output_file = output_dir / 'phiwe_campaign_health.csv'
    df.to_csv(output_file, index=False)
    print(f"  ✓ Created {output_file} ({len(df)} metrics)")
    
    return df

def generate_cohort_analysis(bookings, output_dir):
    """Generate cohort analysis CSV"""
    print("\nGenerating cohort analysis...")
    
    df = analyze_cohorts(bookings)
    
    if len(df) > 0:
        output_file = output_dir / 'phiwe_cohort_analysis.csv'
        df.to_csv(output_file, index=False)
        print(f"  ✓ Created {output_file} ({len(df)} cohorts)")
    else:
        print(f"  ⚠ No cohort data available")
    
    return df

def generate_call_timing_optimized(call_timing, output_dir):
    """Generate optimized call timing CSV"""
    print("\nGenerating call timing optimization...")
    
    df = analyze_call_timing(call_timing)
    
    if len(df) > 0:
        output_file = output_dir / 'phiwe_call_timing_optimized.csv'
        df.to_csv(output_file, index=False)
        print(f"  ✓ Created {output_file} ({len(df)} time slots)")
    else:
        print(f"  ⚠ No call timing data available")
    
    return df

def main():
    """Main execution"""
    import sys
    
    print("="*70)
    print("STRETCHLAB B2C - PIPELINE ENHANCEMENT V5.0")
    print("="*70)
    
    # Get date argument if provided
    date_str = sys.argv[1] if len(sys.argv) > 1 else None
    
    # Load existing data
    data, output_dir = load_existing_csvs(date_str)
    
    # Validate cancellation counts (logs the 28 vs 34 breakdown)
    validate_cancellation_counts(data['bookings'])

    # Generate 6 new CSVs
    generate_benchmarks_comparison(data['calls'], data['bookings'], output_dir)
    generate_revenue_intelligence(data['calls'], data['bookings'], output_dir)
    generate_forecast(data['daily_performance'], output_dir)
    generate_campaign_health(data['calls'], data['bookings'], output_dir)
    generate_cohort_analysis(data['bookings'], output_dir)
    generate_call_timing_optimized(data['call_timing'], output_dir)
    
    print("\n" + "="*70)
    print("✅ ENHANCEMENT COMPLETE!")
    print("="*70)
    print(f"\nOutput directory: {output_dir}")
    print("\nGenerated 6 new CSV files:")
    print("  1. phiwe_benchmarks_comparison.csv")
    print("  2. phiwe_revenue_intelligence.csv")
    print("  3. phiwe_forecast_30_day.csv")
    print("  4. phiwe_campaign_health.csv")
    print("  5. phiwe_cohort_analysis.csv")
    print("  6. phiwe_call_timing_optimized.csv")
    print("\nNext step: Upload ALL CSVs to Loveable")
    print("="*70)

if __name__ == '__main__':
    main()
